config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task=Task.all
    respond_to do |format|
    format.html
    format.js
  end
  end

  def create
    Task.create(task_params)
    @task=Task.all
    respond_to do |format|
    format.html
    format.js
    end

  end

  def edit
   @task=Task.find(params[:id])
  end

  def update
    @task=Task.find(params[:id])
    @task.update_attributes(task_params)
    @task=Task.all
    respond_to do |format|
    format.html { redirect_to root_path }
    format.js { }
    end
  end

  def destroy
    task=Task.find(params[:id])
    task.destroy
    @task=Task.all
    respond_to do |format|
    format.html { redirect_to root_path }
    format.js { }

  end
  end

  private
   def task_params
     params.require(:task).permit(:title, :content)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_alltasks.html.erb
<h2>All Tasks</h2>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Content</th>
            <th>Action</th>

          </tr>
        </thead>
        <tbody>
          <%@task.each do |task|%>
            <tr class="success">
              <td><%= task.title%></td>
              <td><%=task.content%></td>
              <td><%=link_to 'Delete' ,task_path(task),method: :delete,class: 'btn btn-danger',id: "deltask",remote: true,data: { confirm: 'Are you sure?' }%>
              <span><%=link_to 'Edit',edit_task_path(task),remote: true,class:'btn btn-warning'%></span></td>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tasks/_edit.html.erb
<div id="eModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit</h4>
      </div>
      <div class="modal-body" id="edit_form">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/tasks/_edit_tsak.html.erb
<%= form_for @t , remote: true do |f| %>
<div class="form-group">
  <%= f.text_field :title, placeholder: "Place title" %>
</div>

<div class="form-group">
  <%= f.text_field :content, placeholder: "Describe Your Task" %>
</div>

<div class="form-group">
  <%= f.submit class: 'btn btn-default' %>
</div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for Task.new , remote: true do |f| %>
<div class="form-group">
  <%= f.text_field :title, placeholder: "Place title" %>
</div>

<div class="form-group">
  <%= f.text_field :content, placeholder: "Describe Your Task" %>
</div>

<div class="form-group">
  <%= f.submit class: 'btn btn-default' %>
</div>
<% end %>

app/views/tasks/create.js.erb
$('#showtask').html("<%= j render partial: 'alltasks',:@task => @task %>")
   $('#myModal').modal('toggle');
  toastr.success("Task Successfully created")

app/views/tasks/destroy.js.erb
$('#deltask').remove()
$('#showtask').html("<%= j render partial: 'alltasks',locals: {:@task => @task} %>")
toastr.warning("Task Successfully deleted")

app/views/tasks/edit.js.erb
   $('#eModal').modal('show');
   $('#edit_form').html("<%= j render partial: 'edit_tsak', locals:{:@t => @task} %>")

app/views/tasks/index.html.erb
<div class="container">
  <div class="jumbotron">
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Creat Task</button>
    <%=link_to 'Show All Task',tasks_path, class: 'btn btn-info btn-lg',remote: true %>
  </div>
</div>

<%= render 'edit'%>
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create Task Here</h4>
      </div>
      <div class="modal-body">
        <%=render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div class="container" id="showtask"></div>

app/views/tasks/index.js.erb
$('#showtask').html("<%= j render partial: 'alltasks',locals: {:@task => @task} %>")

app/views/tasks/update.js.erb
$('#showtask').html("<%= j render partial: 'alltasks', :@task => @task %>")
$('#eModal').modal('toggle')
toastr.success("Task Successfully Updated")